dist: bionic

language: c

compiler:
    - gcc

addons:
    apt:
        update: true
        packages:
            - build-essential
            - cmake
            - pkgconf
            - wget
            - ca-certificates
            - python3
            - python3-pip
            - python3-setuptools
            - python3-wheel
            - ninja-build
            - lcov

before_install:
    - sudo pip3 install --system meson

before_script:
    - meson -Db_coverage=true build

script:
    - cd build
    - meson test

after_success:
    - bash <(curl -s https://codecov.io/bash)